# Analysis of management-scenario 
# Reads the 1000 ASC files generated by nlrx 

library(raster)
library(dplyr)
library(ggplot2)
library(ggpubr)


# Paths
RUN_DIR <- "management_final_50seeds"
ASC_DIR <- file.path(RUN_DIR, "asc")
MANIFEST <- file.path(RUN_DIR, "ASC_manifest.csv")
OUT_DIR <- file.path(RUN_DIR, "analysis")

dir.create(OUT_DIR, showWarnings = FALSE)

# Read manifest
manifest <- read.csv(MANIFEST, stringsAsFactors = FALSE)

if (nrow(manifest) != 1000) {
  stop("Expected 1000 rows in ASC_manifest.csv; found ", nrow(manifest))
}

manifest$path <- file.path(ASC_DIR, manifest$filename)

if (any(!file.exists(manifest$path))) {
  stop("Some ASC files listed in the manifest are missing.")
}

# Calculate spatial metrics for each ASC
results_list <- vector("list", nrow(manifest))

for (i in seq_len(nrow(manifest))) {

  f <- manifest$path[i]
  cat("Processing", i, "of", nrow(manifest), ":", basename(f), "\n")

  r <- raster(f)

  # Binary occupancy
  r[r > 0] <- 1
  r[is.na(r[])] <- 0

  # 8-neighbour connected components
  r_clump <- r
  r_clump[r_clump == 0] <- NA
  cl <- clump(r_clump, directions = 8)

  sizes <- as.data.frame(freq(cl))
  sizes <- sizes[!is.na(sizes$value), ]

  n_clusters <- if (nrow(sizes) == 0) 0 else nrow(sizes)
  mean_cluster_size <- if (nrow(sizes) == 0) 0 else mean(sizes$count)

  vals <- getValues(r)
  occupied_cells <- sum(vals == 1, na.rm = TRUE)

  results_list[[i]] <- data.frame(
    run_id = manifest$run_id[i],
    random_seed = manifest$random.seed[i],
    siminputrow = manifest$siminputrow[i],
    scenario = manifest$scenario[i],
    tick = manifest$tick[i],
    year = manifest$year[i],
    file = manifest$filename[i],
    occupied_cells = occupied_cells,
    n_clusters = n_clusters,
    mean_cluster_size = mean_cluster_size,
    stringsAsFactors = FALSE
  )
}

results <- bind_rows(results_list)

# scenario labels
results <- results %>%
  mutate(
    treatment = case_when(
      scenario == "baseline" ~ "Baseline",
      grepl("^low_", scenario) ~ "Low intensity",
      grepl("^intermediate_", scenario) ~ "Intermediate intensity",
      grepl("^high_eradication_", scenario) ~ "High intensity (eradication)",
      TRUE ~ NA_character_
    ),
    zone = case_when(
      scenario == "baseline" ~ "Baseline",
      grepl("_100m$", scenario) ~ "100 m",
      grepl("_200m$", scenario) ~ "200 m",
      grepl("_400m$", scenario) ~ "400 m",
      TRUE ~ NA_character_
    )
  )

results$treatment <- factor(
  results$treatment,
  levels = c(
    "Baseline",
    "Low intensity",
    "Intermediate intensity",
    "High intensity (eradication)"
  )
)

results$zone <- factor(
  results$zone,
  levels = c("Baseline", "100 m", "200 m", "400 m")
)

results$year <- factor(
  results$year,
  levels = c(2035, 2045)
)

write.csv(
  results,
  file.path(OUT_DIR, "results_analysis_figure6.csv"),
  row.names = FALSE
)

# Summary table
summary_results <- results %>%
  group_by(year, treatment, zone) %>%
  summarise(
    n = n(),
    mean_n_clusters = mean(n_clusters),
    median_n_clusters = median(n_clusters),
    sd_n_clusters = sd(n_clusters),
    cluster_size_mean = mean(mean_cluster_size),
    median_cluster_size = median(mean_cluster_size),
    sd_cluster_size = sd(mean_cluster_size),
    mean_occupied_cells = mean(occupied_cells),
    .groups = "drop"
  ) %>%
  rename(mean_cluster_size = cluster_size_mean)

write.csv(
  summary_results,
  file.path(OUT_DIR, "summary_figure6.csv"),
  row.names = FALSE
)

# Plot style
theme_pub <- function(base_size = 15) {
  theme_minimal(base_size = base_size) +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      axis.title = element_text(face = "bold"),
      axis.text.x = element_text(angle = 30, hjust = 1),
      legend.title = element_text(face = "bold"),
      legend.position = "right",
      plot.title = element_text(face = "bold", hjust = 0.5),
      strip.background = element_blank(),
      strip.text = element_text(face = "bold")
    )
}

pal <- c(
  "Baseline" = "#BBBBBBB3",
  "Low intensity" = "#91BFDBB3",
  "Intermediate intensity" = "#FC8D59B3",
  "High intensity (eradication)" = "#66C2A5B3"
)

# Figure 6A: number of clusters
plot_clusters <- ggplot(
  results,
  aes(x = zone, y = n_clusters, fill = treatment)
) +
  geom_boxplot(
    width = 0.8,
    outlier.shape = NA,
    colour = "black",
    size = 0.3
  ) +
  scale_fill_manual(values = pal, drop = FALSE) +
  facet_wrap(~ year, nrow = 1) +
  labs(
    x = "Treatment-zone width",
    y = "Number of clusters",
    fill = "Treatment intensity"
  ) +
  theme_pub()

# Figure 6B: mean cluster size
plot_mean_cluster <- ggplot(
  results,
  aes(x = zone, y = mean_cluster_size, fill = treatment)
) +
  geom_boxplot(
    width = 0.8,
    outlier.shape = NA,
    colour = "black",
    size = 0.3
  ) +
  scale_fill_manual(values = pal, drop = FALSE) +
  facet_wrap(~ year, nrow = 1) +
  labs(
    x = "Treatment-zone width",
    y = "Mean cluster size (cells)",
    fill = "Treatment intensity"
  ) +
  theme_pub()

figure6_AB <- ggarrange(
  plot_clusters,
  plot_mean_cluster,
  ncol = 1,
  nrow = 2,
  align = "v",
  common.legend = TRUE,
  legend = "right",
  labels = c("A", "B")
)

ggsave(
  file.path(OUT_DIR, "Figure6_AB.pdf"),
  figure6_AB,
  width = 10,
  height = 10
)

ggsave(
  file.path(OUT_DIR, "Figure6_AB.png"),
  figure6_AB,
  width = 10,
  height = 10,
  dpi = 300
)

cat("\nFinished.\n")
cat("Results:", file.path(OUT_DIR, "results_analysis_figure6.csv"), "\n")
cat("Summary:", file.path(OUT_DIR, "summary_figure6.csv"), "\n")
cat("Figure:", file.path(OUT_DIR, "Figure6_AB.pdf"), "\n")
